# Restaurant Application services configuration
# Includes backend, landing site, and web app services
# Usage: docker-compose -f docker-compose.yml -f docker-compose.app.yml up

version: '3.8'

services:
  backend:
    image: restaurant_backend:latest
    container_name: restaurant_backend
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-restaurant_user}:${POSTGRES_PASSWORD:-restaurant_pass}@postgres:5432/${POSTGRES_DB:-restaurant_db}
      REDIS_URL: redis://redis:6379
      CLERK_JWKS_URL: ${CLERK_JWKS_URL}
      SECRET_KEY: ${SECRET_KEY}
      ENVIRONMENT: ${ENVIRONMENT:-production}
    volumes:
      - ./docker/volumes/uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - restaurant_network
    restart: unless-stopped

  landing:
    image: restaurant_landing:latest
    container_name: restaurant_landing
    ports:
      - "${LANDING_PORT:-3000}:3000"
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:5000/api}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - restaurant_network
    restart: unless-stopped

  web:
    image: restaurant_web:latest
    container_name: restaurant_web
    ports:
      - "${WEB_PORT:-5173}:5173"
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:5000/api}
      VITE_CLERK_PUBLISHABLE_KEY: ${VITE_CLERK_PUBLISHABLE_KEY}
      VITE_STRIPE_PUBLISHABLE_KEY: ${VITE_STRIPE_PUBLISHABLE_KEY}
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - restaurant_network
    restart: unless-stopped