# Base Docker Compose configuration
# This file only defines networks and basic configuration
# Use with other compose files for complete setup

version: '3.8'

networks:
  restaurant_network:
    driver: bridge
    name: restaurant_network